select * from "DimCustomers"
select * from "DimProducts"
select * from "FactOrderItems"
select * from "FactOrders"
select * from "FactPayment"



1. How many total orders has UrbanCart received so far? 

SELECT
	count(*) AS "Total_order"
FROM "FactOrders"



2. How many unique customers have placed at least one order?

SELECT 
    COUNT(DISTINCT customer_id) AS Unique_Customers
FROM "FactOrders";



3. Which cities generate the highest number of orders? 

SELECT
	c.city,
	COUNT(*) AS total_orders
FROM
	"FactOrders" AS o
	LEFT JOIN "DimCustomers" AS c ON o.customer_id = c.customer_id
GROUP BY
	1
ORDER BY
	2 DESC;



4.  What percentage of customers have placed more than one order? 

WITH
	customer_orders AS (
		SELECT
			customer_id,
			COUNT(order_id) AS order_amount_by_customer
		FROM
			"FactOrders"
		GROUP BY
			customer_id
	)
SELECT
	ROUND(COUNT(CASE WHEN order_amount_by_customer > 1 THEN 1 END) * 100.0 / COUNT(*),2) AS repeat_customer_percentage
FROM
	customer_orders;



5. What is the monthly trend of total orders over time? 

SELECT
    EXTRACT(MONTH FROM order_date::date) AS order_by_month,
	COUNT(order_id) AS total_orders
FROM
	"FactOrders"
GROUP BY
	order_by_month
ORDER BY
	order_by_month;



6. What is the total revenue generated by UrbanCart? 

SELECT
	sum(p.unit_price * i.quantity) AS Total_revenue
FROM
	"DimProducts" AS p
	JOIN "FactOrderItems" AS i ON p."product_id" = i."product_id"



7. Which product categories contribute the most to total revenue? 

SELECT
	p.category,
	SUM(p.unit_price * i.quantity) AS revenue_by_category
FROM
	"DimProducts" AS p
	JOIN "FactOrderItems" AS i 
	ON p."product_id" = i."product_id"
GROUP BY 1
ORDER BY 2 DESC
LIMIT 8;



8. Which individual products generate the highest revenue? 

SELECT
	p.product_name,
	SUM(p.unit_price * i.quantity) AS revenue_by_category
FROM
	"DimProducts" AS p
	JOIN "FactOrderItems" AS i 
	ON p."product_id" = i."product_id"
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;



9. What is the average order value (AOV) and Average Basket Size? 

WITH
	order_value AS (
		SELECT
			i.order_id,
			SUM(p.unit_price * i.quantity) AS order_revenue,
			SUM(i.quantity) AS baskets_size
		FROM
			"DimProducts" AS p
			JOIN "FactOrderItems" AS i ON p."product_id" = i."product_id"
		GROUP BY
			1
	)
SELECT
	round(avg(order_revenue), 2) AS average_order_value,
	round(avg(baskets_size), 2) AS average_basket_size
FROM
	order_value



10. Which products are at risk of stock-out due to high sales volume and low inventory?

SELECT
	p.product_name,
	p.stock,
	SUM(i.quantity) AS units_sold,
	ROUND(SUM(i.quantity) * 1.0 / p.stock, 2) AS demand_vs_stock
FROM
	"DimProducts" AS p
	JOIN "FactOrderItems" AS i ON p."product_id" = i."product_id"
GROUP BY
	1,
	2
HAVING
	SUM(i.quantity) > p.stock
ORDER BY
	2 ASC



11. Which customers contribute the highest total revenue?

SELECT
	c.full_name,
	SUM(oi.quantity * p.unit_price) AS total_revenue
FROM
	"DimCustomers" AS c
	JOIN "FactOrders" AS o ON c.customer_id = o.customer_id
	JOIN "FactOrderItems" AS oi ON o.order_id = oi.order_id
	JOIN "DimProducts" AS p ON oi.product_id = p.product_id
GROUP BY
	c.full_name
ORDER BY
	total_revenue DESC
LIMIT
	5;



12. What is the average number of products purchased per order?

WITH
	order_items AS (
		SELECT
			order_id,
			sum(quantity) OVER (PARTITION BY order_id) AS total_order
		FROM "FactOrderItems"
	)
SELECT
	round(avg(total_order), 2) AS avg_product_purchase_per_order
FROM
	order_items



13.Do male and female customers show different purchasing patterns by category?

SELECT
	c.gender,
	p.category,
	SUM(oi.quantity * p.unit_price) AS total_revenue,
	SUM(oi.quantity) AS total_units_sold
FROM
	"DimCustomers" AS c
	JOIN "FactOrders" AS o ON c.customer_id = o.customer_id
	JOIN "FactOrderItems" AS oi ON o.order_id = oi.order_id
	JOIN "DimProducts" AS p ON oi.product_id = p.product_id
GROUP BY
	c.gender,
	p.category
ORDER BY
	2;



14. Which cities have the highest average order value?

WITH
	highest_avg_order AS (
		SELECT
			c.city,
			o.order_id,
			sum(oi.quantity * p.unit_price) AS total_revenue
		FROM
			"DimCustomers" AS c
			JOIN "FactOrders" AS o ON c.customer_id = o.customer_id
			JOIN "FactOrderItems" AS oi ON o.order_id = oi.order_id
			JOIN "DimProducts" AS p ON oi.product_id = p.product_id
		GROUP BY 1, 2
	)
SELECT
	city,
	round(avg(total_revenue), 2) AS avg_order_value
FROM
	highest_avg_order
GROUP BY city
ORDER BY 2 DESC



15. How does customer purchasing behavior change over time since account creation?

SELECT
	CASE
		WHEN o.order_date::DATE - c.created_at::DATE BETWEEN 0 AND 30  THEN '0–30 days'
		WHEN o.order_date::DATE - c.created_at::DATE BETWEEN 31 AND 60  THEN '31–60 days'
		WHEN o.order_date::DATE - c.created_at::DATE BETWEEN 61 AND 90  THEN '61–90 days'
		ELSE '90+ days'
	END AS customer_age,
	COUNT(DISTINCT o.customer_id) AS active_customers,
	COUNT(o.order_id) AS total_orders,
	ROUND(SUM(oi.quantity * p.unit_price), 2) AS total_revenue
FROM
	"DimCustomers" c
	JOIN "FactOrders" o ON c.customer_id = o.customer_id
	JOIN "FactOrderItems" oi ON o.order_id = oi.order_id
	JOIN "DimProducts" p ON oi.product_id = p.product_id
GROUP BY
	customer_age
ORDER BY
	customer_age;



16. Which payment methods are used most frequently?

SELECT
	method,
	count(*) AS method_used
FROM
	"FactPayment"
GROUP BY method
ORDER BY 2 DESC


17. Is there any relationship between payment method and order status?

SELECT
    p.method AS payment_method,
    o.status AS order_status,
    COUNT(o.order_id) AS total_orders,
    ROUND(COUNT(o.order_id) * 100.0 / SUM(COUNT(o.order_id)) OVER (PARTITION BY p.method),2)
	AS percentage_within_method
FROM "FactPayment" p
JOIN "FactOrders" o
    ON p.order_id = o.order_id
GROUP BY 1, 2
ORDER BY 1, 3 DESC;



18.Do certain cities prefer specific payment methods?

SELECT
    c.city,
    p.method AS payment_method,
    COUNT(o.order_id) AS total_orders,
    ROUND(COUNT(o.order_id) * 100.0 / SUM(COUNT(o.order_id)) OVER (PARTITION BY c.city),2 ) AS percentage_within_city
FROM "DimCustomers" c
JOIN "FactOrders" o
    ON c.customer_id = o.customer_id
JOIN "FactPayment" p
    ON o.order_id = p.order_id
GROUP BY 1, 2
ORDER BY 3 DESC;



19. Are higher-value orders associated with specific payment methods?

WITH
	order_value AS (
		SELECT
			p.method AS payment_method,
			oi.order_id,
			SUM(oi.quantity * pr.unit_price) AS order_value
		FROM
			"FactOrderItems" oi
			JOIN "DimProducts" pr ON oi.product_id = pr.product_id
			JOIN "FactPayment" p ON oi.order_id = p.order_id
		GROUP BY
			p.method, oi.order_id
	)
SELECT
	payment_method,
	ROUND(AVG(order_value), 2) AS avg_order_value
FROM
	order_value
GROUP BY 1
ORDER BY 2 DESC;



20. What is the average number of items per order by payment method?

WITH
	order_items AS (
		SELECT
			p.method AS payment_method,
			oi.order_id,
			SUM(oi.quantity) AS items_per_order
		FROM
			"FactOrderItems" oi
			JOIN "FactPayment" p ON oi.order_id = p.order_id
		GROUP BY
			p.method,
			oi.order_id
	)
SELECT
	payment_method,
	ROUND(AVG(items_per_order), 2) AS avg_items_per_order
FROM
	order_items
GROUP BY 1
ORDER BY 2 DESC;



21. Which products are most frequently ordered together?

WITH
	top_paired_products AS (
		SELECT
			oi1.product_id AS product_1,
			oi2.product_id AS product_2,
			COUNT(*) AS times_ordered_together
		FROM
			"FactOrderItems" AS oi1
			JOIN "FactOrderItems" oi2 ON (
				oi1.order_id = oi2.order_id
				AND oi1.product_id < oi2.product_id
			)
		GROUP BY 1, 2
		ORDER BY 3 DESC
		LIMIT 10
	)
SELECT
	p1.product_name AS "product_1",
	p2.product_name AS "product_2",
	times_ordered_together
FROM
	top_paired_products AS tpr
	LEFT JOIN "DimProducts" AS p1 ON tpr.product_1 = p1.product_id
	LEFT JOIN "DimProducts" AS p2 ON tpr.product_2 = p2.product_id
ORDER BY 3 DESC


22. Which products combination are most frequently ordered together?

WITH order_products AS (
SELECT
    oi.order_id,
    ARRAY_AGG(p.product_name ORDER BY p.product_name) 
		AS product_combination,
    COUNT(DISTINCT oi.product_id) AS product_count
    FROM "FactOrderItems" oi
    JOIN "DimProducts" p
        ON oi.product_id = p.product_id
    GROUP BY oi.order_id
)
SELECT
    product_combination,
    COUNT(*) AS times_ordered
FROM order_products
WHERE product_count >= 2
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


23. Are there product pairs that consistently drive higher order values?

WITH
	order_data AS (
		SELECT
			oi.order_id,
			p.product_name,
			SUM(oi.quantity * p.unit_price) OVER (PARTITION BY oi.order_id) AS order_value
		FROM
			"FactOrderItems" oi
			JOIN "DimProducts" p ON oi.product_id = p.product_id
	)
SELECT
	d1.product_name AS product_1,
	d2.product_name AS product_2,
	ROUND(AVG(d1.order_value), 2) AS avg_order_value
FROM
	order_data d1
	JOIN order_data d2 ON d1.order_id = d2.order_id
	AND d1.product_name < d2.product_name
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;


24. Which product combinations could be recommended as bundles to increase
revenue?

WITH
	order_data AS (
		SELECT
			oi.order_id,
			p.product_name,
			SUM(oi.quantity * p.unit_price) OVER (PARTITION BY oi.order_id) AS order_value
		FROM
			"FactOrderItems" oi
			JOIN "DimProducts" p ON oi.product_id = p.product_id
	)
SELECT
	d1.product_name AS product_1,
	d2.product_name AS product_2,
	sum(d1.order_value) AS product_price
FROM
	order_data d1
	JOIN order_data d2 ON d1.order_id = d2.order_id
	AND d1.product_name < d2.product_name
GROUP BY 1, 2
HAVING
	COUNT(DISTINCT d1.order_id) >= 5
ORDER BY 3 DESC
LIMIT 10;   



25. Based on product co-occurrence and customer behavior, which products should
UrbanCart promote together to maximize cross-selling opportunities?

WITH
	order_data AS (
		SELECT
			oi.order_id,
			p.product_name,
			SUM(oi.quantity * p.unit_price) OVER (PARTITION BY oi.order_id) AS order_value
		FROM
			"FactOrderItems" oi
			JOIN "DimProducts" p ON oi.product_id = p.product_id
	)
SELECT
	d1.product_name AS product_1,
	d2.product_name AS product_2,
	ROUND(AVG(d1.order_value), 2) AS avg_order_value
FROM
	order_data d1
	JOIN order_data d2 ON d1.order_id = d2.order_id
	AND d1.product_name < d2.product_name
GROUP BY 1, 2
HAVING
	COUNT(DISTINCT d1.order_id) >= 5
ORDER BY 3 DESC
LIMIT 10;








select * from "DimCustomers"
select * from "DimProducts"
select * from "FactOrderItems"
select * from "FactOrders"
select * from "FactPayment"



























